"""Generate the Flutter palette source from the same JSON imported by Vue."""
import json
import pathlib
import sys
root = pathlib.Path(__file__).resolve().parents[1]
data = json.loads((root / 'design-system/questrace/themes.json').read_text())
target = root / 'mobile/flutter_app/lib/app/theme_catalog.dart'
source = "// Generated by scripts/generate-themes.py. Do not edit.\nimport 'dart:convert';\n\nconst sharedThemeJSON = r'''" + json.dumps(data, ensure_ascii=False, indent=2) + "''';\nfinal Map<String, dynamic> themeCatalog = jsonDecode(sharedThemeJSON);\n"
if '--check' in sys.argv:
    if target.read_text() != source:
        raise SystemExit('Theme catalog is out of date')
else:
    target.write_text(source)
